//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlwf_10EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmTurleri
    {
        public FilmTurleri()
        {
            this.Filmler = new HashSet<Filmler>();
        }
    
        public int FilmTurNo { get; set; }
        public string TurAd { get; set; }
        public string Aciklama { get; set; }
        public bool Silindi { get; set; }
    
        public virtual ICollection<Filmler> Filmler { get; set; }
    }
}
