//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlwf_10EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        public Filmler()
        {
            this.FilmSatis = new HashSet<FilmSatis>();
        }
    
        public int FilmNo { get; set; }
        public string FilmAd { get; set; }
        public int FilmTurNo { get; set; }
        public string Yonetmen { get; set; }
        public string Oyuncular { get; set; }
        public string Ozet { get; set; }
        public int Miktar { get; set; }
        public bool Varmi { get; set; }
    
        public virtual FilmTurleri FilmTurleri { get; set; }
        public virtual ICollection<FilmSatis> FilmSatis { get; set; }
    }
}
