//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlwf_10EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmSatis
    {
        public int SatisNo { get; set; }
        public System.DateTime Tarih { get; set; }
        public int FilmNo { get; set; }
        public int MusteriNo { get; set; }
        public int Adet { get; set; }
        public decimal BirimFiyat { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Filmler Filmler { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
