//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlwf_10EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VideoMarketEntities : DbContext
    {
        public VideoMarketEntities()
            : base("name=VideoMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Filmler> Filmler { get; set; }
        public DbSet<FilmSatis> FilmSatis { get; set; }
        public DbSet<FilmTurleri> FilmTurleri { get; set; }
        public DbSet<Musteriler> Musteriler { get; set; }
    }
}
