//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSaglikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public Kategoriler()
        {
            this.AltKategoriler = new HashSet<AltKategoriler>();
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int id { get; set; }
        public string kategoriad { get; set; }
        public string aciklama { get; set; }
        public bool silindi { get; set; }
    
        public virtual ICollection<AltKategoriler> AltKategoriler { get; set; }
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}
