//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSaglikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int urunid { get; set; }
        public string urunkodu { get; set; }
        public string urunad { get; set; }
        public int urunkategorino { get; set; }
        public int urunaltkategorino { get; set; }
        public int miktar { get; set; }
        public decimal urunfiyat { get; set; }
        public string urunbilgisi { get; set; }
        public string resimyolu1 { get; set; }
        public string resimyolu2 { get; set; }
        public bool silindi { get; set; }
    
        public virtual AltKategoriler AltKategoriler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
