//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSaglikProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public int id { get; set; }
        public string kullaniciad { get; set; }
        public string sifre { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public System.DateTime tarih { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string ilce { get; set; }
        public string il { get; set; }
        public string tckimlikno { get; set; }
    }
}
