//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_12EntityOkul
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OKULEntities : DbContext
    {
        public OKULEntities()
            : base("name=OKULEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ogrenciler> Ogrenciler { get; set; }
        public DbSet<Ogretmenler> Ogretmenler { get; set; }
        public DbSet<Siniflar> Siniflar { get; set; }
    }
}
