//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_12EntityOkul
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflar
    {
        public Siniflar()
        {
            this.Ogrenciler = new HashSet<Ogrenciler>();
        }
    
        public int ID { get; set; }
        public string SinifAd { get; set; }
        public System.DateTime BasTarihi { get; set; }
        public System.DateTime BitTarihi { get; set; }
        public byte Mevcut { get; set; }
        public Nullable<int> OgretmenID { get; set; }
    
        public virtual ICollection<Ogrenciler> Ogrenciler { get; set; }
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
